{% set version = "v1.0.beta11" %}

package:
  name: micmac
  version: {{ version }}

source:
  fn: micmac-{{ version }}.tar.gz
  url: https://github.com/micmacIGN/micmac/archive/{{ version }}.tar.gz
  sha256: 77f4ffaeb92829f972d7c24820b469c4505e4bf048c23a0a8a1feadd686745b1
  patches:

build:
  number: 1

requirements:
  build:
    - cmake
    - openmp 4.0.0
    - xorg-libx11
    - perl 5.22.2.1
  run:
    - openmp 4.0.0
    - xorg-libx11
    - imagemagick
    - proj4
    - perl 5.22.2.1

test:
    imports:
    commands:

about:
  home: https://github.com/micmacIGN/micmac
  license: CeCILL-B
  summary: Free open-source photogrammetry software tool
