{% set version = "8db9f6f" %}

package:
  name: micmac
  version: {{ version }}

source:
  git_url: https://github.com/micmacIGN/micmac.git
  git_rev: 8db9f6f4229326fc47766466db505eda13a0d1da

build:
  number: 1

requirements:
  build:
    - cmake
    - openmp 4.0.0
    - xorg-libx11
    - perl 5.22.2.1
  run:
    - openmp 4.0.0
    - xorg-libx11
    - imagemagick
    - proj4
    - perl 5.22.2.1

test:
    imports:
    commands:

about:
  home: https://github.com/micmacIGN/micmac
  license: CeCILL-B
  summary: Free open-source photogrammetry software tool
